TalentBox/sequel-rails

lib/sequel_rails/railtie.rb

Just like ActiveRecord and Mongoid do. So we can patch Sequel::Model after initializing.

Execute load hooks for Sequel::Model

---

lib/sequel_rails/railtie.rb
lib/sequel_rails/railties/database.rake

Because of rails_admin, I had to pull ActiveRecord into a project that I'd already configured for Sequel with sequel-rails. ```rake db:migrate``` would fail.
This pull request allows the ```db:``` rake namespace to be configured using something like ```config.sequel.load_database_tasks = :sequel```, but preserves existing behaviour.
Now I (and capistrano, with some work) can say ```rake sequel:migrate``` and things work as expected.

allow db: namespace to be reconfigured to something else, eg sequel:

---

lib/sequel_rails/configuration.rb

Sequel expects the config hash to have symbolized keys, but sequel-rails is passing it a HashWithIndifferentAccess which returns strings if you inspect it (e.g. config.keys will give you an array of strings instead of symbols).
Sequel.connect() internally attempts to fix this but it only works on the outer hash, it doesn't fix any nested hashes.
This prevents the sharding :servers option from working.
Example: http://sequel.jeremyevans.net/rdoc/files/doc/sharding_rdoc.html#label-Single+Read-Only+Slave-2C+Single+Master
It should be as simple as adding:
```
servers:
read_only:
host: other_server
```
to your database.yml but this won't work unless the keys are symbols when passed to Sequel.connect

Make sure the Sequel.connect hash has symbols as keys.

---

lib/sequel_rails/railtie.rb

Hey,
I went a little too trigger happy on the last PR, when doing `rake db:migrate` for example, it seems Spring is defined but Spring::Application is not, and it makes the thing crash. Fixed with this.

Fix bug if Spring is defined but Spring::Application is not

---

lib/action_dispatch/middleware/session/sequel_store.rb

ENV_SESSION_OPTIONS_KEY is no longed defined in the Rack:Session::Abstract module of Rack 2.0, so I replaced it with it's original value.

preliminary rails 5 and rack 2 support

---

lib/sequel_rails/storage.rb
lib/sequel_rails/storage/abstract.rb
spec/lib/sequel_rails/storage_spec.rb

Right now this works fine for all Sequel connections, but breaks for all rake tasks since the URL isn't parsed. This ends up being a deal breaker when using `sequel-rails` with a `config/database.yml` that looks like this:
```
...
development:
url:  <%= ENV['DATABASE_URL'] %>
...
```
This adds support to the Storage helpers, which fixes the rake tasks.

Support specifying 'url' in configuration files

---

lib/generators/sequel/model/templates/migration.rb.erb
lib/generators/sequel/model/templates/model.rb.erb

Generated files have trailing spaces that some linters like rubocop complain about.

Trim trailing spaces at templates

---

README.md
ci/rails-5.0.gemfile

It seems to me that Rails 5 is already fully supported by sequel-rails - at least it worked for me in a new project. Am I missing something? If it does, here is a PR to update the README and the Travis matrix.
Refs  #104 #105 #110
When merged, please also update the project oneliner on the top of the GitHub page.

Rails 5 release

---

lib/sequel_rails/railties/database.rake

`rake db:schema:load` has a malformed string for an error message. The message should display the name of the file and also properly namespace the display of the `migrate` task's name (e.g. `rake sequel:migrate`), but because the error string is single-quoted, this doesn't happen and the intended interpolated values are instead interpreted as literals.

Fix string interpolation syntax

---

lib/sequel_rails/storage/postgres.rb
spec/lib/sequel_rails/storage/postgres_spec.rb

This patch makes sequel-rails behave a bit more like ActiveRecord.
`db:setup` should be more resilient in that it won't fail to drop a database that doesn't exist.
Certain combinations of database.yml, ENV["DATABASE_URL"] and JDBC will now succeed when the port defaults to zero.

Handle missing database

---

lib/sequel_rails/railtie.rb
lib/sequel_rails/railties/database.rake
spec/spec_helper.rb

When running `rake db:create` with a default sequel-rails installation (testing this with Rails 5.1.4), the following exception occurs:
```
rake aborted!
Sequel::DatabaseConnectionError: PG::ConnectionBad: FATAL:  database "my_rails_app_development" does not exist
```
This happens because by default a connection is made to the configured database. This patch checks to see if we are running inside a Rake tasks and does not automatically connect if we do.
The Rake tasks themselves then call `db_for_current_env` if they need a connection to the database for the current environment. This only sets up a database connection in Rake tasks as needed.
This solves the exception on `db:create` for us and others remain working.

Fix db:create rake tasks

---

lib/sequel_rails/railtie.rb

Prior to this commit, running bin/rails db:create:all in a new Rails
app with sequel-rails configured to replace ActiveRecord resulted in
this error:
Sequel::DatabaseConnectionError: PG::ConnectionBad: FATAL:  database "rails_app_development" does not exist
It then failed to create either the development or test databases.
This commit includes db:create:all in the commands checked to enable
skip_connect and avoid attempting to connect to the database before it's
been created.
Previously only db:create was checked. I don't want to make the check
too permissive so I'm specifying the full command and still checking
the ARGV array of command line arguments.
This extends the fix I originally submitted with #148.

Fix Sequel::DatabaseConnectionError on db:create:all task

---

lib/sequel_rails/migrations.rb

Currently when you run `bin/rails db:migrate` on a fresh rails app
created with: `rails new appname --skip-active-record` you don't get a
`db/migrate` directory which results in this exception:
```
rails aborted!
Errno::ENOENT: No such file or directory @ dir_initialize - .../db/migrate
.../oss/sequel-rails/lib/sequel_rails/migrations.rb:9:in `migrate'
.../oss/sequel-rails/lib/sequel_rails/railties/database.rake:166:in `block (2 levels) in <top (required)>'
.../sandbox/appname/bin/rails:9:in `require'
.../sandbox/appname/bin/rails:9:in `<top (required)>'
.../sandbox/appname/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```
With this fix SequelRails will catch this issue before it's …

Raise useful exception when db/migrate directory is absent

---

lib/sequel_rails/railties/database.rake

**Note**: I promise I'm not trying to DDoS you with Pull Requests. :-)
This is essentially the same issue as #156. An easy fix and useful
feedback for users who created a Rails app without ActiveRecord and
will not have any `db/` directory.
The feedback is:
```
$ bin/rails db:schema:dump
The db/ directory doesn't exist, please create it.
```
Compare to what happened before this commit:
```
$ bin/rails db:schema:dump
rails aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - .../sandbox/appname/db/schema.rb
.../oss/sequel-rails/lib/sequel_rails/railties/database.rake:26:in `initialize'
.../oss/sequel-rails/lib/sequel_rails/railties/database.rake:26:in `open'
.../oss/sequel-rails/lib/sequel_rails/railties/database.rake:26:in `block (3 levels) in <top (required)>' …
```

Check that db/ exists before running db:schema:load

---

lib/sequel_rails/configuration.rb
lib/sequel_rails/db_config.rb
spec/lib/sequel_rails/configuration_spec.rb

This change allows `config.sequel.servers` to propagate properly to
Sequel::connect. It also blacklists this option from being sent to
an adapter via url query param.
The use-case is documented here:
https://github.com/jeremyevans/sequel/blob/master/doc/sharding.rdoc#primaryreplica-configurations-and-database-sharding

Allow 'servers' to propagate to Sequel connection

---

lib/sequel_rails/railties/database.rake
spec/lib/sequel_rails/railties/database_rake_spec.rb

This PR adds some rake tasks for managing the sessions table (`db:sessions:clear` and `db:sessions:trim`). This tasks are very similar to the ones found in [ActiveRecord::SessionStore](
https://github.com/rails/activerecord-session_store/blob/d7a918cc2b24b4261fead06538d7d8f8d8b2a1d1/lib/tasks/database.rake#L9-L200).

feat: add db:sessions clear and trim rake tasks

---

lib/action_dispatch/middleware/session/sequel_store.rb

This PR silences the logger when reading and writing sessions to the database. This mimics behavior found in the [ActiveRecord::SessionStore](https://github.com/rails/activerecord-session_store/blob/d7a918cc2b24b4261fead06538d7d8f8d8b2a1d1/lib/action_dispatch/session/active_record_store.rb#L69-L78) class.
Not sure how to best test this. Any suggestions?

feat: silence logger for sequel session store

---

lib/sequel_rails/migrations.rb

This PR adds `allow_missing_migration_files` for `dump` command missed in prev PR.
ref: https://github.com/TalentBox/sequel-rails/pull/172

Use migrator with allow_missing_migration_files opt for dump schema

---

lib/generators/sequel/migration/templates/migration.rb.erb

Rubocop has rule https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/FrozenStringLiteralComment
which turned on by default.
@JonathanTron WDYT?

Add frozen_string_literal to migration template

---

lib/sequel_rails/railtie.rb

We had removed the `SpringSupport` module, but it's still being referenced on initialization. We remove this code, and move the `Sequel.after_fork` call to the "sequel.spring" initializer.
Thanks to @xymbol for pointing it out.

Remove references to removed SpringSupport

---

lib/sequel_rails/storage/abstract.rb
lib/sequel_rails/version.rb
spec/lib/sequel_rails/storage/postgres_spec.rb

When we try to recreate a database using the `rails db:drop db:create` command with a non-existent database, we will crash when the `Sequel::Model#db` method is called. This happens because array `Sequel::DATABASES` is empty ([this](https://github.com/jeremyevans/sequel/issues/1727) change in Sequel).
I think we just need to check a size of `Sequel::DATABASES` before processing `#drop`.

Database drop fix for Sequel (>= 5.38.0)

---

README.md
lib/sequel_rails/configuration.rb
spec/lib/sequel_rails/configuration_spec.rb

Use `after_connect` hook in the proper way with each connection within the connection pool ([sequel doc](https://sequel.jeremyevans.net/rdoc/classes/Sequel/ConnectionPool.html#attribute-i-after_connect))
Currently, there is `after_connect` executed only once for the Sequel connection instance, but it's not executed when creating new connection within connection pool
With using sequel-rails with rails and multithreaded webserver (for example Puma) there is a need to utilize a connection pool for multiple connections. 
Let's say that we want to set statement_timeout for all connections in the connection pool.
```
config.sequel.after_connect = proc do |db|
db.execute('SET statement_timeout = 30000;')
end
```
So with max_connections => 5 and running 
```
5.times{ Thread.new{ puts DB['SHOW …
```

chore: use after_connect hook within connection pool for each new connection

---

index.html

As it says on the tin. 
The Github Pages are rather outdated in terms of referencing the supported Rails version numbers. I also noted the `gemspec` is rather outdated (I'll open a separate PR) and the Github repository description is also referring to older, unsupported (?) Rails versions. 
Question: are you using the Google Analytics tracking code at all? Otherwise, I'd advise simply removing it (which can be done in a separate PR).

Brings GH pages up to date

---

lib/sequel_rails/railtie.rb

Currently this check doesn't work with `rails db:create` command since rails replaces ARGV. This fix makes it work for both `rails` and `rake` versions.

Fix database_create_command? check

---

lib/sequel_rails/railties/log_subscriber.rb
spec/lib/sequel_rails/railties/log_subscriber_spec.rb

Simplify how we handle `binds` in `LogSubscriber` to support bound variables and prepared statements.

183 handle bound variables and prepared statement

---

README.md
lib/sequel_rails/railtie.rb

In case if app does not have db yet, commands db:create[env],
db:test:prepare, db:setup did not work, because they required
connection to not existed database. This commit adds ability to run
these commands regardless of whether the database exists or not.

Allow to use commands db:test:prepare, db:setup without created DB

---

lib/sequel_rails/railties/database.rake

Disconnecting all connections before attempting to drop the database solves a very common and annoying issue for me, where open connections created by the Rails application are still present when attempting to drop the test database.
It manifests itself as:
```
dropdb: error: database removal failed: ERROR:  database "rails-app-test" is being accessed by other users
DETAIL:  There is 1 other session using the database.
Couldn't drop database for environment test
createdb: error: database creation failed: ERROR:  database "rails-app-test" already exists
Could not create database for test.
```
This change fixes the problem.

Disconnect database connections before attempting to drop database

---

lib/sequel_rails/railtie.rb

It seems `SequelRails::Railties::LogSubscriber.count` and `SequelRails::Railties::LogSubscriber.runtime` don't work properly with API-only applications.

Include ControllerRuntime in ActionController::API
